name: ipa
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9 
  - cudatoolkit>=11.3
  - faiss-gpu

  - pip
  - pillow
  - scipy
  - scikit-image

  - pip:
    - git+https://github.com/openai/CLIP.git
    - numpy==1.26.4 # keep under 2.0 for faiss compatibility

    - torch==2.0.1
    - torchvision==0.15.2
    - torchaudio==2.0.2
    - accelerate

    - einops
    - matplotlib
    - opencv-python
    - pandas
    - scikit-learn

    - huggingface-hub
    - gdown

    - omegaconf
    - wandb
